# -*- mode: perl -*-
#!/usr/bin/perl -w

use strict;
use Config qw(myconfig config_sh config_vars);
use CGI;
use Data::Dumper;
use warnings;


my $filename = 'temp.txt';
open(my $fh, '>', $filename);
print $fh "My first report generated by perl\n";
close $fh;






